export { ButtonSkeleton, NavbarSkeleton } from './Navbar.skeleton'
export { ProfileErrorSkeleton, ProfileSkeleton } from './Profile.skeleton'
export { ProfilePageSkeleton } from './ProfilePage.skeleton'
export { ResultPageSkeleton } from './ResultPage.skeleton'
export { WrapTaskSkeleton } from './WrapTask.skeleton'
